version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Seoul"
    commit-message:
      prefix: "deps(frontend)"
    target-branch: "dev"
    groups:
      all-frontend:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Seoul"
    commit-message:
      prefix: "deps(backend)"
    target-branch: "dev"
    groups:
      all-backend:
        patterns:
          - "*"